### ISSUE TITLE
WebVM is actually not Linux but GNU

### ISSUE THREAD

**Issue by f0o** [leaningtech/webvm#10]
Semantics are important. WebVM does not run the Linux Kernel but has some of the GNU Distribution ported.

It shouldn't advertise itself as Linux when it isn't even running it.

Ref: https://www.gnu.org/gnu/linux-and-gnu.html

**Comment by sere** [comment]
Hello f0o

Yes, we don't indeed run the Linux kernel. We are not "only" a GNU system either, though. Our system is API and ABI compatible with the Linux kernel, and we are running a Debian environment on top of our system.

We are revising our description to reflect more accurately where we stand in relation to the Linux kernel, GNU/Linux and Debian.

**Comment by f0o** [comment]
Considering it closed after the Readme update.

Thanks! :)
