### ISSUE TITLE
Custom binary results in fault 555564a7, execution hangs

### ISSUE THREAD

**Issue by michael-nestler** [leaningtech/webvm#101]
Hello!
I'm trying to get the [BCPL compiler](https://www.cl.cam.ac.uk/~mr10/BCPL.html) binaries running on WebVM. I have managed to get a basic debian image running, but the compiler binary itself hangs and needs to be  terminated via Ctrl+C. The console shows a fault, although I can't interpret this message:
```
cxcore.js:1 CODE AT OFFSET c5 f8
cxcore.js:1 TODO: FAULT 555564a7
cxcore.js:1 CODE c5 f8 57
``` 
### Reproducability
This is the dockerfile I'm using for the custom image:
```dockerfile
FROM --platform=i386 i386/debian:buster as build

WORKDIR /root

RUN apt-get clean && apt-get update && apt-get -y upgrade
RUN apt-get -y install gcc build-essential curl

# Steps described in Chapter 12 in the BCP manual https://www.cl.cam.ac.uk/~mr10/bcplman.pdf
# Additionally, I'm adding a '-m32' flag to gcc just to be sure the resulting binary is i386 compatible
RUN curl https://www.cl.cam.ac.uk/~mr10/BCPL/bcpl.tgz -o bcpl.tgz && mkdir -p distribution && tar zxvf bcpl.tgz -C distribution && rm bcpl.tgz
RUN cd distribution/BCPL/cintcode && . ./os/linux/setbcplenv && sed -i '1s/^/CFLAGS+=-m32 \n/' Makefile && cat Makefile && make clean && make

FROM --platform=i386 i386/debian:buster

RUN useradd -m user && echo "user:password" | chpasswd
WORKDIR /home/user/
COPY --from=build /root/distribution/BCPL/cintcode /home/user/distribution/BCPL/cintcode
ENV HOME="/home/user" TERM="xterm" USER="user" SHELL="/bin/bash" EDITOR="vim" LANG="en_US.UTF-8" LC_ALL="C"
RUN echo 'root:password' | chpasswd
RUN printf '#!/bin/sh\n. /home/user/distribution/BCPL/cintcode/os/linux/setbcplenv && cintsys $@' > /home/user/cintsys && chmod +x /home/user/cintsys
ENTRYPOINT [ "/home/user/cintsys" ]
```
Locally, running this image opens the `cintsys` TUI:
```
❯ docker run --rm -it --platform i386 bcpl

BCPL 32-bit Cintcode System (13 Dec 2023)
Estimated 160000 Cintcode instructions per milli-second
0.000>
```
However, on WebVM, the console shows the error mentioned above and execution simply hangs until terminated

If you'd like to inspect the generated binary, use the dockerfile above (the binary will lie at `/home/user/distribution/BCPL/cintcode/bin/cintsys` in the container) or use the attached `cintsys`
[cintsys.zip](https://github.com/leaningtech/webvm/files/15062538/cintsys.zip) (please don't run this binary locally unless you trust strangers on the internet! 😉).

### Speculation
Although I use the 32-bit target for BCPL and even patched it to add a `-m32` to the GCC flags, it's possible this is an issue of architecture mismatch. If you can point me in the right direction based on the errors, I'd be very greatful.
It's also possible that this is simply using unsupported instruction, although I don't believe the compiler is doing anything esoteric.

### Versions
I tried both the latest `cx.js` as well as `https://cheerpxdemos.leaningtech.com/publicdeploy/20230517_94/cx.js`, same issue with both distributions.

I can provide any further information if necessary. Thank you!

**Comment by saarikoski-jules** [comment]
The issue you're seeing is due to CheerpX not supporting VEX prefixed instructions. To get your program to work, you should disable the feature.
