### ISSUE TITLE
What you type isn't always echoed to the screen

### ISSUE THREAD

**Issue by ta2016** [leaningtech/webvm#102]
My browser: Google Chrome Version 126.0.6478.127 (Offizieller Build) (64-Bit)
My OS: Windows 10 Business Version 22H2 (Build 19045.4651)

What I type into webvm.io isn't always echoed to the screen. But the simple commands I tried are executed properly as far as I can tell.
Also, pressing TAB to autocomplete doesn't seem to work.

**Comment by saarikoski-jules** [comment]
Hi, thanks for reporting this issue. We'll look into the echo.

About tab completion, I'm unable to reproduce. Could you tell me exactly what you're trying to do when autocomplete fails?

**Comment by ta2016** [comment]
Hi, thanks for the fast response. Regarding tab completion I have to admit
that I myself am unable to repro now. I'd like to take back that part of my
report.

**Comment by gabrielsroka** [comment]
i'm noticing this, too. Chrome and Firefox on Windows 10.

**Comment by corneliusroemer** [comment]
Also came here to report. Brave on Android 14.

**Comment by alexp-sssup** [comment]
Thanks everybody for your feedback, the bug is now fixed and a new build of webvm is deployed. Please notice that due to CDN caching it might take a bit for the new version to be visible everywhere.
