### ISSUE TITLE
Provide an example in the README about how to run a custom native executable

### ISSUE THREAD

**Issue by rNeomy** [leaningtech/webvm#11]
There is no documentation on how to attach a binary and run it in the README.

**Comment by sere** [comment]
At the moment it's not supported. We might introduce it in the future.

**Comment by Alex-A137** [comment]
> At the moment it's not supported. We might introduce it in the future.

hey it's the future now

**Comment by yuri91** [comment]
You can use the newly added network support for this: https://github.com/leaningtech/webvm/blob/main/README.md#how-to-enable-networking

Once you enable networking via Tailscale, you can use `scp`, or `wget`, to get a file from another machine in your Tailscale network.
