### ISSUE TITLE
filesystem access

### ISSUE THREAD

**Issue by belaviyo** [leaningtech/webvm#110]
Hi,

Would it be possible to run a Linux binary in the VM. There is need to be able to access the filesystem from JS for writing the binary and also reading the generated output file.

**Comment by saarikoski-jules** [comment]
Hi, thanks for reaching out about this. At the moment there are a few issues with some filesystems updating correctly, but it is on our todo list in the near future. We will get back to this issue when these problems have been addressed.

**Comment by saarikoski-jules** [comment]
Hi, thanks for your patience. We've fixed some issues and what you would like to do works now.

You can take a look at the documentation for the old filesystem documentation here: https://cheerpj.com/docs/guides/File-System-support. We are currently in the middle of a filesystem API revamp that will improve the user experience, but for now using these will work.

For your purposes, you can add a new file to the `/str` filesystem by using the `cheerpOSAddStringFile` API, documented here: https://cheerpj.com/docs/reference/cheerpOSAddStringFile Then you can copy your file to home and do what you need to do.

To extract your output you will need to have mounted the `/files` filesystem during creation time, by adding `{type:"cheerpOS",dev:"/files",path:"/mnt"}` to the `CheerpXApp.create` call. Copy your output file to /mnt. Then you can use the `cheerpOSGetFileBlob` API to extract your file like this: `cheerpOSGetFileBlob([], "/files/output", function(blob) { .. }`

**Comment by belaviyo** [comment]
Thanks! I tried using the master branch, and although `cheerpOSAddStringFile("/str/fileName.txt", "Some text in a JS String");` doesn't throw errors, the folder ("/str") doesn't exist. I tested it with `debian_mini_20230519_5022088024.ext2`.

I was hoping for an API that could handle JS `File` objects in the OS, not just string files. There are many situations where you need to push a large file into the OS for inspection or data extraction. In Emscripten's worker mode, we can pass JS `File` objects without adding them to the heap, allowing you to work with large files in the worker. However, Emscripten's filesystem isn't very flexible. I was hoping cheerpOS would offer a more flexible solution. Ideally, there would be an asynchronous JS function that accepts a path as an argument and passes an ArrayBuffer to the engine for both reading and writing.

**Comment by saarikoski-jules** [comment]
In the current webvm, the str filesystem is mounted to `/data`. If you write with a cheerpOS function to `/str`, you'll find the file within webvm in `/data`. This will be addressed with the upcoming api changes.

It's technically possible to implement `File` objects, but at the moment it's not where our immediate focus is. `cheerpOSAddStringFile` can also take a Uint8Array if that would make what you're trying to do a little bit easier.

**Comment by belaviyo** [comment]
> `cheerpOSAddStringFile` can also take a Uint8Array

My point is that writing large files to memory isn't effective. Instead, the approach should be to use the file pointer to read chunks as needed, rather than copying the entire file to the operating system.

Example:

```bash
file /data/index.mp4
index.mp4: ISO Media, MP4 v2 [ISO 14496-14]
```

This command only read the header section of the large file.

**Comment by saarikoski-jules** [comment]
Ah I understand. I can of course see the value of this feature, but unfortunately right now our priorities lay elsewhere (full graphical linux boot).
