### ISSUE TITLE
Network is not enabled

### ISSUE THREAD

**Issue by ZachXu** [leaningtech/webvm#111]
I deployed page in the gitlab my own fork and start the webVM successfully. 
However i cannot access the internet inside. 
Even i click the 'Connect via Tailscale' button login into Tailscale. 
I will see an ip showing 100.101.93.84

but why i type 'apt update'
it still looks like cannot connect the network, any other things i have to do?

**Comment by saarikoski-jules** [comment]
To access the public internet you will need also need to set up a Tailscale exit node.  You can look at the instructions on how to do so here: https://github.com/leaningtech/webvm/blob/main/docs/Tailscale.md. 

Installing packages via apt is currently not supported, the best way to currently do that is by editing the Dockerfile to install the packages you need.
