### ISSUE TITLE
why doesnt webvm work?

### ISSUE THREAD

**Issue by Dimpfucse135** [leaningtech/webvm#117]
everytime i load into the vm, it just freezes

**Comment by saarikoski-jules** [comment]
Hi, could you provide more information about your setup? Are you trying to load our hosted online version, your own github pages or a local one? If you open the console in your browser, are you seeing any logs or any errors in the network tab?

**Comment by saarikoski-jules** [comment]
I'm closing this issue as there is not enough information to work on this. If you're still having trouble, feel free to open a new issue with more information.
