### ISSUE TITLE
Attempting to write to /data/ hangs

### ISSUE THREAD

**Issue by qwergle** [leaningtech/webvm#118]
Trying to run `touch /data/thingy` or `echo "Hello, World" > /data/text` causes WebVM to hang. Since having DevTools open while running one of those commands shows a failed assertion in the process of creating the file, I'm guessing that an error occurs due to /data being read-only, as in #92?

**Comment by saarikoski-jules** [comment]
Thank you for reporting this issue, it's now been fixed in the latest version.
