### ISSUE TITLE
Graphical

### ISSUE THREAD

**Issue by aHIPPOz** [leaningtech/webvm#122]
Hello, would it be possible to install a graphical environment like wayland + gnome-shell on WebVM and then use a vnc server to host it and then open the localhost URL in the browser to have access to a graphical debian in the browser? (PS: sorry if the translation is bad I did it with google translate)

**Comment by alexp-sssup** [comment]
Graphical desktop support is coming very soon, but it will be based on Xorg at first. Support for Wayland will be included in the future when support for 3D graphics is added.

Please note that with the upcoming support VNC will not be required. The desktop will boot directly in the tab.

**Comment by aHIPPOz** [comment]
ok thanks a lot but isn't there a workaround in the meantime?

**Comment by yigitkonur** [comment]
It is more required as Anthropic release computer use API, it will have lots of use case @alexp-sssup 

https://docs.anthropic.com/en/docs/build-with-claude/computer-use

**Comment by alexp-sssup** [comment]
Hold on tight, graphics support is coming in 2 or 3 weeks

**Comment by alexp-sssup** [comment]
Support for graphics has been released

Please read the full announcement here: https://labs.leaningtech.com/blog/webvm-20

New Alpine / Xorg / i3 demo: https://webvm.io/alpine.html
