### ISSUE TITLE
su password doesn't work on local deployment

### ISSUE THREAD

**Issue by ungkuamer** [leaningtech/webvm#125]
Tried to use the password to log in as root, the password "password" worked on the webvm.io but does not work on my machine - Authentication failure. All other commands worked fine and console does not produce any error.

**Comment by alexp-sssup** [comment]
The most likely cause i that the root password is not actually set in your local setup. How is the local image built?

**Comment by ungkuamer** [comment]
Followed the instructions under 'Local Deployment' section. Cloned the repo into my desktop, edited the variables and ext2 image as per the instructions and used nginx to start the server. Empty password also does not work. Any idea on which point or where do I need to set the root password?

**Comment by alexp-sssup** [comment]
The `debian_mini` image does not have the passwords configured. You can change the `uid`/`gid` on the JavaScript side to run the shell with root privileges. You can also follow build a new version of the `debian_mini` image by following the instructions here: https://github.com/leaningtech/webvm?tab=readme-ov-file#fork-deploy-customize

To make the image downloadable don't forget to select the "Upload GitHub release" workflow option.
