### ISSUE TITLE
Grep not working

### ISSUE THREAD

**Issue by jkooij** [leaningtech/webvm#126]
Thanks for the great work.

I was testing some commands on https://webvm.io/, and noticed that `grep` does not seem to produce any output.
For example, searching for lines containing `a` in the `fibonacci.py` example generates no output:
```bash
user@:~$ grep a examples/python3/fibonacci.py 
user@:~$
```
Adding additional switches, such as `-c`, doesn't change this behavior.

Passing input via a pipe results in an error message:
```bash
user@:~$ cat examples/python3/fibonacci.py | grep a
grep: (standard input): Function not implemented
user@:~$ 
```

Finally, simply running `grep --help` _does_ print a normal help message to the terminal.
I couldn't find any related issues on this issue tracker, so perhaps it is a new bug?

**Comment by alexp-sssup** [comment]
The problem has been fixed in the new version of WebVM. Make sure to clear your local caches (or use Incognito/Private mode) to see the version.

**Comment by gavanderhoorn** [comment]
@alexp-sssup: out of curiosity, could you link to a specific commit or PR which shows the fix?

**Comment by alexp-sssup** [comment]
While WebVM is FOSS, the underlying virtualization engine (CheerpX) is not, so commits are not public. The underlying problem was that, somewhat surprisingly, `grep` has special behavior when the output is `/dev/null`. The was a mistake in the implementation that made `grep` think all devices were `/dev/null`.

**Comment by jkooij** [comment]
Wow, I am amazed by the speed this was fixed.
Bravo to the @alexp-sssup and the leaningtech team for the impressive work!
