### ISSUE TITLE
how to install a library using python?

### ISSUE THREAD

**Issue by Dimpfucse135** [leaningtech/webvm#129]

**Comment by alexp-sssup** [comment]
Can you clarify what command you are trying to run and what is the problem you are seeing? WebVM is a complete Debian distribution and you can install packages as normal using `apt-get install`

**Comment by Dimpfucse135** [comment]
i mean like in python, i tried to use pip install and it didnt work

**Comment by alexp-sssup** [comment]
WebVM comes with `python3` installed, so you should use `pip3`. If you want to install python2 you can do so by using `apt-get install python-pip`. To install packages you will need to be `root`, you can do so by using the `su` command.

The password for `root` is `password`

**Comment by Dimpfucse135** [comment]
thx, this helped me
