### ISSUE TITLE
which git fails due to shebang

### ISSUE THREAD

**Issue by bk2204** [leaningtech/webvm#13]
Running `which git` fails:

```
user@:~$ which git
bash: /usr/bin/which: /bin/sh: bad interpreter: Invalid argument
```

This appears to be because `#! /bin/sh` (in `which`) is not recognized as a valid shebang.  While it is very common to omit a space after the `#!`, spaces have been permitted since Unix Version 8, and Linux allows them.

**Comment by sere** [comment]
Hello, thanks for the report. We indeed handle this case incorrectly. We added this bug to our bucket list

**Comment by Alex-A137** [comment]
how about fixing it now

**Comment by alexp-sssup** [comment]
The problem is now fixed
