### ISSUE TITLE
Exception thrown in WebAssembly layer when running `ps aux` in webvm.io

### ISSUE THREAD

**Issue by ggoodman** [leaningtech/webvm#131]
Hey team, first of all: I'm a huge fan and avid reader of your release posts and technical explorations.

I was playing around with webvm.io and it appears that a fairly simple operation reliably triggers a trap in WASM and debug path in JavaScript.

```sh
# Type the following in the webvm.io shell to reproduce.
ps aux
```

Stack trace visible in dev tools (after stepping over `debugger` statement 😝).

```
Unexpected exit RuntimeError: remainder by zero
    at wasm://wasm/00016d42:wasm-function[26]:0x1ace
    at wasm://wasm/02fd4e9e:wasm-function[4]:0x29f
    at wasm://wasm/006d1962:wasm-function[2006]:0xd9772
    at wasm://wasm/006d1962:wasm-function[2007]:0xd9811
    at abB (blob:https://webvm.io/809c9501-e715-411b-a5be-006b2ed8eb67:1:62256)
    at blob:https://webvm.io/809c9501-e715-411b-a5be-006b2ed8eb67:1:113872
    at abD (blob:https://webvm.io/809c9501-e715-411b-a5be-006b2ed8eb67:1:62124)
    at wasm://wasm/006d1962:wasm-function[2410]:0xf5629
    at MessagePort.EA (blob:https://webvm.io/809c9501-e715-411b-a5be-006b2ed8eb67:1:62996)
```

**Comment by alexp-sssup** [comment]
Thanks for reporting this and for your kind words. @saarikoski-jules please take a look when you have a chance

**Comment by alexp-sssup** [comment]
We have improved the correctness of the information in /proc/ which fixes this crash
