### ISSUE TITLE
Add Java support

### ISSUE THREAD

**Issue by jabrena** [leaningtech/webvm#14]
Hi, I would like that webvm could have java inside.

**Comment by Alex-A137** [comment]
i agree, because i want to try to play minecraft on webvm lol

**Comment by jabrena** [comment]
Great news.

I suggest to add `JBang` support
https://www.jbang.dev

**Comment by nanaian** [comment]
WebVM supports Java, we just happen not install it by default.

There are a number of options here:

- Use [CheerpJ](https://labs.leaningtech.com/cheerpj), our HTML5 JVM. [You can try it in your browser here.](https://javafiddle.leaningtech.com/)
- [Enable networking](https://github.com/leaningtech/webvm/blob/main/docs/Tailscale.md) and `apt-get install default-jdk default-jre`
- [Deploy your own fork of WebVM](https://github.com/leaningtech/webvm#fork-deploy-customize) and add `default-jdk` and `default-jre` in the Dockerfile
