### ISSUE TITLE
Not loading in Firefox Ubuntu

### ISSUE THREAD

**Issue by anidotnet** [leaningtech/webvm#18]
Webvm.io is not loading inside Firefox 96.0 (64bit) in Ubuntu 20.04.3 LTS. This is error message I am seeing in browser console

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://disks.leaningtech.com/webvm_20220131.ext2. (Reason: CORS request did not succeed). Status code: (null).

**Comment by sere** [comment]
Hello, are you accessing webvm.io or are you serving it locally with your own server?

If it's the latter, please use `nginx` with the provided `nginx.conf` to create the server.

If you see this issue on webvm.io, can I ask you to try on a fresh Firefox profile with no extensions installed?

**Comment by anidotnet** [comment]
I tried it in incognito mode in Firefox, it gave the same error. I can't create a fresh Firefox profile as I use it daily. But I tried with Chrome, it worked.

**Comment by pixeltris** [comment]
FYI Firefox incognito wouldn't work anyway as IndexedDB isn't supported in it. It'll hit `idbTrap` in `cheerpOS.js`.

**Comment by sere** [comment]
You can create a fresh Firefox profile while maintaining the current one by going to the page about:profiles and clicking on "Create a New Profile". Please see https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles?redirectslug=profile-manager-create-and-remove-firefox-profiles&redirectlocale=en-US for reference.

**Comment by anidotnet** [comment]
Same issue. I created new profile but same result there also.

**Comment by sere** [comment]
I have an hard time reproducing this. Could you please attach a screenshot of the network tab with the failing request expanded?
