### ISSUE TITLE
Empty /proc filesystem; causes ps, pgrep, etc. commands not working

### ISSUE THREAD

**Issue by rigarash** [leaningtech/webvm#22]
Currently, /proc filesystem is empty. This means that we cannot run "ps" (and various other process related application such as pgrep, killall, fuser, ...) now.

**Comment by sere** [comment]
Thanks for the report. We are aware of this;  procfs is still unimplemented in CheerpX, so we cannot provide the /proc filesystem.

While it's technically feasible, it's not in our plans for the time being. In case you'd like such functionality for a commercial project, we are happy to discuss at info@leaningtech.com

**Comment by hello-smile6** [comment]
> Thanks for the report. We are aware of this; procfs is still unimplemented in CheerpX, so we cannot provide the /proc filesystem.
> 
> While it's technically feasible, it's not in our plans for the time being. In case you'd like such functionality for a commercial project, we are happy to discuss at [info@leaningtech.com](mailto:info@leaningtech.com)

Really, not everything is about money.

**Comment by crankycyclops** [comment]
> > Thanks for the report. We are aware of this; procfs is still unimplemented in CheerpX, so we cannot provide the /proc filesystem.
> > While it's technically feasible, it's not in our plans for the time being. In case you'd like such functionality for a commercial project, we are happy to discuss at [info@leaningtech.com](mailto:info@leaningtech.com)
> 
> Really, not everything is about money.

Are you volunteering?

**Comment by alexp-sssup** [comment]
Basic support for `/proc/`, `ps`, `pgrep`, `top` and similar programs is available in the current build of https://webvm.io.
