### ISSUE TITLE
Is this any different from jslinux?

### ISSUE THREAD

**Issue by songbug1024** [leaningtech/webvm#25]
[jslinux](https://bellard.org/jslinux/)

I integrated node(v14.8.0) to jslinux "riscv64-Fedora 33 (Linux)-Console"，Same problem with WebVM, such as fs slow to load, high memory usage, DNS getaddrinfo EAI_AGAIN error...

![image](https://user-images.githubusercontent.com/6696585/154886359-82574aec-17de-460d-9c1e-30e70603fab0.png)

**Comment by alexp-sssup** [comment]
CheerpX is designed to be practically and commercially useful by achieving a high level of performance. You can verify this yourself by benchmarking some payload against the two VMs.

The limitations are similar because they reflect the underlying capabilities of the browser platform.
