### ISSUE TITLE
Where's your source code?

### ISSUE THREAD

**Issue by hello-smile6** [leaningtech/webvm#26]
You use numerous binaries licensed under the GNU Public License. So, where's the source code? Or, _where's your lawyer?_

**Comment by alexp-sssup** [comment]
The GPL license only propagates to derivative works. CheerpX/WebVM is not derivative work of any of the available executables, but a generic execution environment that can run any application.

The executables themselves are actually static assets, and identical to the ones shipped as part of the Debian distribution. If you are interested in the source code of such executable you can obtain them using the Debian package manager (i.e. the `apt-get source` command)

Please consider the following analogies:
* Running a GPL executable on VMWare does not cause VMWare to become GPLed.
* Running a GPL executable on Windows does not cause Windows to become GPLed.
* Running a GPL executable on an Intel CPU does not cause the CPU design to become GPLed.
