### ISSUE TITLE
Logo/mascot [nice to have]

### ISSUE THREAD

**Issue by TheGamer1002** [leaningtech/webvm#3]
Hi there!

I'm thinking there should be a logo, or as the cool kids call it, a "favicon" for the website. Perhaps some ASCII art or a nice letter art? I can't draw but wanted to have the idea for considering.
Thanks!

**Comment by rinkydevi** [comment]
hey @TheGamer1002 ! I can contribute to this issue, how can i proceed?

**Comment by TheGamer1002** [comment]
Hi there! I’m thinking about the Internet globe symbol (🌐) enclosing the Debian logo. I’ll make a quick sketch.

**Comment by TheGamer1002** [comment]
![65EA1CB8-2E96-4350-9611-CD695AD9C066](https://user-images.githubusercontent.com/48131223/152710561-b7b7db1d-e53d-4bd5-8a9d-df963d3cce69.jpeg)
Alright, here we go! It’s not too amazing but it’s the best I can do with what I have. Thanks again!

**Comment by rinkydevi** [comment]
alright i can make and provide a favicon for this issue

**Comment by sere** [comment]
Guys, the favicon and the logo are already there, and are our (LeaningTech) responsibility to change. We won't be accepting any external logo.

**Comment by TheGamer1002** [comment]
Alright, thank you! Sorry for the inconvenience.

**Comment by rinkydevi** [comment]
hey @sere ! it is fine, all the best for your logo and favicon!!
