### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by cottons-kr** [leaningtech/webvm#34]
This is too slow that I cant use it well. I used Chrome 101 on Ubuntu 20.04.4

Is it slow only for me?

**Comment by robtech21** [comment]
This is a virtual machine running on a web browser... this feat on it's own is pretty tremendous. Of course it's slow.

**Comment by cottons-kr** [comment]
I tried it on i7-3770, 12GB of RAM. I did not know WASM is very very slow and I thought WASM is really fast so can use on VM.

**Comment by hello-smile6** [comment]
> This is a virtual machine running on a web browser... this feat on it's own is pretty tremendous. Of course it's slow.

It's **not** tremendous. There's also [v86](https://copy.sh/v86), which **actually works**.
