### ISSUE TITLE
Put files into VM

### ISSUE THREAD

**Issue by eduardoplnascimento** [leaningtech/webvm#35]
How can I copy a file from my server to the VM?

I tried to run commands like '/bin/touch' to create a file, however I can't put contents into the file, because the CheerpX run command with echo prints everything in the terminal:

Javascript Code:
`await cheerpx.run('/bin/echo', ['"Hello World"',  '>', '/var/www/index.html'], {});`

Output:
`"Hello World" > /var/www/index.html`

The commands wget and curl are not available either. Is there a way to put a file into the VM using the API?

**Comment by saarikoski-jules** [comment]
Hi and thanks for your curiosity!

You can create files in this way, but you'll need to execute the commands using bash. You're probably looking for something more in the lines of this:
`await cheerpx.run('/bin/bash', ["-c", "/bin/echo Hello World > /var/www/index.html"], env)`
