### ISSUE TITLE
make: env: Timestamp out of range

### ISSUE THREAD

**Issue by domesticmouse** [leaningtech/webvm#4]
```console
user@:~$ cd examples/c/
user@:~/examples/c$ make
cc  -o link link.c
make: link: Timestamp out of range; substituting 1969-12-31 23:59:59.999999999
cc  -o waitpid waitpid.c
make: waitpid: Timestamp out of range; substituting 1969-12-31 23:59:59.999999999
cc  -o env env.c
make: env: Timestamp out of range; substituting 1969-12-31 23:59:59.999999999
make: helloworld.c: Timestamp out of range; substituting 1969-12-31 23:59:59.999999999
make: Warning: File 'helloworld.c' has modification time 1.6e+10 s in the future
cc  -o helloworld helloworld.c
make: helloworld: Timestamp out of range; substituting 1969-12-31 23:59:59.999999999
cc  -o openat openat.c
make: openat: Timestamp out of range; substituting 1969-12-31 23:59:59.999999999
make: warning:  Clock skew detected.  Your build may be incomplete.
user@:~/examples/c$ 
```

**Comment by domesticmouse** [comment]
This may be due to the fact that I am in Brisbane, Australia. Timezones are a PITA, amirite?

**Comment by carlopi** [comment]
I do reproduce from the Netherlands, tomorrow a colleague will take a look, thanks for signaling this.

**Comment by sere** [comment]
Hello, thanks for your report. Fortunately, it shouldn't be a timezone problem ;) All the dates / times are internal to the machine, and in UTC.

What I believe it's happening is a mismatch between the date the file(s) are saved with and the current date. We have a known bug where if you create a file with touch you'll get a creation date that goes back to the '90s, and this seems to be based on the same underlying issue.
