### ISSUE TITLE
which command is provided, but fails with an error regarding shell interpreter

### ISSUE THREAD

**Issue by michael-mayes** [leaningtech/webvm#40]
Using  WebVM (build 20220726)

The gcc command can be found, but attempts to use the which command to find it fails with an error regarding shell interpreter:
![image](https://user-images.githubusercontent.com/11037231/191088074-2d4113be-ef3c-4fe5-8d03-9439dfdeeb28.png)

**Comment by saarikoski-jules** [comment]
Duplicate of #13
