### ISSUE TITLE
[Safari ?] Hangs randomly

### ISSUE THREAD

**Issue by Parura5726** [leaningtech/webvm#42]
Basically the title, when I try to use vim or just the terminal, the website hangs, the only way to fix it is reloading. js console shows a debug message of the format `Fault addr cb8bb1a4, ip 556ece35, tid 4` followed by `Fault from Inode 28281`.

| Tool | Version|
|-----|--------|
|Safari| 15.4 (16613.1.17.1.13, 16613)|
|Macos|Big Sur 11.6.2|
|Model|M1 Macbook Air 2020|

**Comment by alexp-sssup** [comment]
Can the issue be reproduced with our latest release?

**Comment by Parura5726** [comment]
Unfortunately it still does.

**Comment by carlopi** [comment]
Could you possibly run the same experiment either with Firefox (non-Incognito) and/or Chrome/Chromium (on the same device)?

**Comment by carlopi** [comment]
I believe the problem here is that Safari 15.4 had a couple of stubble WebAssembly bugs (eg https://bugs.webkit.org/show_bug.cgi?id=237180) that you are most probably hitting against.

I did run some test on a IPhone with 15.6, and WebVM seems to work as expected.

Would it be possible for you to give it a try from a different machine and / or have your browser updated?

**Comment by Parura5726** [comment]
Nope, last test was run on 16.0, but i retested it anyways and it still hangs, this time while running a compilation using gcc, not vim.

**Comment by alexp-sssup** [comment]
Although we could never reproduce it locally we have fixed many bugs over the last few months. Can this problem still be reproduced?

**Comment by nanaian** [comment]
Can't seem to reproduce any hanging on Safari 16.1 (18614.2.9.1.12), macOS 13.0 (22A380), M1 Macbook Air 2020.

`vim`:

<img width="1448" alt="Screenshot 2023-06-08 at 00 02 21" src="https://github.com/leaningtech/webvm/assets/9429556/5834847c-d84d-4791-944e-712bb157ca91">

`gcc` took a few minutes to cold start, but worked:
<img width="756" alt="Screenshot 2023-06-08 at 00 05 13" src="https://github.com/leaningtech/webvm/assets/9429556/b1e0efb1-cb67-4e5c-afa9-a144d8867d51">

(Not sure what's going on with the `user` and `sys` `time` results there, but I'd imagine that's unrelated to this issue?)

**Comment by alexp-sssup** [comment]
> Not sure what's going on with the user and sys time

The data structure is simply not populated and then mis-printed by user space, it is not a problem.

Closing this issue, it's likely that whatever problem was there originally has been fixed in the meantime
