### ISSUE TITLE
Can't save file made in nano

### ISSUE THREAD

**Issue by cyborgdennett** [leaningtech/webvm#44]
Hi, I try to edit a file in nano. And when I save, it hangs on choose name of file. Pressing Enter does nothing.

![image](https://user-images.githubusercontent.com/40475862/194575802-2b96c289-7b69-4cf2-a25a-6414ee1dd08b.png)

version: GNU nano 3.2

**Comment by cyborgdennett** [comment]
I can just cancel, and choose to not save the file, but saving does not work. Also pressing Enter in edit mode fails to make newline

**Comment by MMK21Hub** [comment]
Can confirm. As a workaround I've been using vim :upside_down_face:

**Comment by gzz2000** [comment]
Also confirm here. Vim works well. But even a `cat <<EOF >file.txt` will hang indefinitely. There must be some syscall bug in the fake filesystem.
