### ISSUE TITLE
Support to execute JS and Wasm natively in browser without nodejs and cheerpx in between

### ISSUE THREAD

**Issue by twischer** [leaningtech/webvm#46]
With this feature it would be possible to only recompile applications with high CPU or memory usage to JS or Wasm instead of X86 binary. All other applications of the operating system could stay as X86 binary applications.

**Comment by alexp-sssup** [comment]
This falls outside the scope of WebVM. The purpose of our technology is to run x86 Linux applications. A third-party integrator may decide to implement hybrid solutions using our APIs only in certain cases.
