### ISSUE TITLE
allow alternative network proxies?

### ISSUE THREAD

**Issue by Jan69** [leaningtech/webvm#49]
tailscale requires you to set up another device, AND sign in, to use it, perhaps a low-priority feature suggestion could be e.g. a websocket -> TCP proxy, which could be done using e.g. https://github.com/zquestz/ws-tcp-proxy (there's a lot of options for various proxies, I've not checked if this particular one is suitable)

also, perhaps easier: **allow running our OWN tailscale network**, using https://github.com/juanfont/headscale which would allow using a fully self-hosted tailscale network (it has an embedded DERP server), it's perfectly fine to default to normal tailscale, but it'd be very nice to have an option to not depend on other services, so you could run it e.g. completely offline, but be able to access your LAN, for example

there's a lot of options, but websocket -> tcp, or self-hosted tailscale network, are the first ones that come to mind (it's understandable you don't want responsibility for everyone's traffic, but also, why should we be required to trust a random third-party company, to get basic networking? not to mention the requirement to have a desktop or server that you can install tailscale onto, to HAVE any networking)

**Comment by yuri91** [comment]
Hi @Jan69 !

Allowing a self-hosted Headscale was in the plan from the beginning, but to avoid complicating the UI we left it out initially.

I agree that it's a useful feature, so I just added a way to use it by providing some arguments to the URL of the page. It should be live now.

You can find more info in the [readme](https://github.com/leaningtech/webvm#how-to-login-to-a-self-hosted-tailscale-network-headscale).

About supporting different kind of proxies: As you say, we really don't want to provide our own public proxy, so some sort of setup on the part of the user will always be needed.

We don't have immediate plans to add more providers, but the network stack is decoupled from the Tailscale solution, so it's possible that we will do it at some point.

I am closing this issue, but feel free to reopen it if you have further questions.
