### ISSUE TITLE
Any hosting/installation instructions?

### ISSUE THREAD

**Issue by phlummox** [leaningtech/webvm#52]
It seems like the code in the repo cannot be directly hosted on a web server in its current state.

A number of spots in the code hard-code the URL <https://cheerpxdemos.leaningtech.com/publicdeploy/CX_VERSION/cx.js>, but this is not actually a working URL – it gives an HTTP 404 error. For instance, one spot where it occurs is:

https://github.com/leaningtech/webvm/blob/1e5b9bcea16dc0c3d92ad1dd18a0dcb939a9336b/tinycore.html#L253

which was introduced in commit 1e5b9bcea16dc0c3d92ad1dd18a0dcb939a9336b.

Presumably, the "CX_VERSION" should be replaced by a valid version number (e.g. `20221125`, which was what commit 1e5b9bcea16dc0c3d92ad1dd18a0dcb939a9336b replaced, or `20230116`, which is what the version deployed at https://webvm.io/ currently uses).

Perhaps you could include a mention of this in the README, and suggest where people might find valid version numbers?

(Also, if the above bug is fixed, by e.g. running `sed -i 's/CX_VERSION/20230116/g' *.html`, then the `getSharedArrayBufferMissingMessage` in index.html seems to be wrongly triggered:

https://github.com/leaningtech/webvm/blob/1e5b9bcea16dc0c3d92ad1dd18a0dcb939a9336b/index.html#L128

But I'll report that as a separate issue.)

**Comment by saarikoski-jules** [comment]
Thank you for reporting this. I've added instructions on how to self host to the README as you requested. If you follow the steps there, you shouldn't get a SharedArrayBuffer error, but please open a new issue if it continues to occur.

**Comment by phlummox** [comment]
Awesome, many thinks for that. Will do.
