### ISSUE TITLE
Unable to get network to run

### ISSUE THREAD

**Issue by tennox** [leaningtech/webvm#54]
Hey :)
This looks pretty amazing! :heart_eyes: 

Would love to try the feasibility of running a demo of an app inside webvm (automatically installed via nix), but don't manage to get network support working.

I set up my laptop as exit node in tailscale:
![image](https://user-images.githubusercontent.com/2084639/224439078-c88ff3af-1e51-4dc5-9ce1-aa2c55b66f39.png)

and logged in to tailscale via webvm.io - but I don't get network to work:

![Screenshot from 2023-03-10 23-19-53](https://user-images.githubusercontent.com/2084639/224439148-6d3dc0b0-5b9d-424a-b0be-d76bf7ee8076.png)

Also found something related to webvm IP happening in tailscale console:
```
Accept: ICMPv4{100.119.232.97:0 > 100.103.154.203:0} 93 ok out
Accept: ICMPv4{100.119.232.97:0 > 100.103.154.203:0} 72 ok out
```

## other question:
And while I'm already asking questions: How likely is it that the core feature (a shell with networking) will be open source?

**Comment by yuri91** [comment]
Hi @tennox !

Did you also run your exit node with `tailscale up --advertise-exit-node` ?
you can double check by doing `tailscale status` on the exit node. it should say "offers exit node".

If you did, to further debug what's going on, can you reach the exit node itself?

Example:

```
# in the exit node
nc -l 9999 -vvv
```

```
# in webvm
nc <tailscale ip of exit node> 9999 -vvv
```

?

**Comment by Niek** [comment]
I had something similar. Just advertising as exit node is not enough, you need to edit the route settings and manually slide the Exit Node button to enable.

**Comment by alexp-sssup** [comment]
Closing due to lack of information
