### ISSUE TITLE
CTRL+C not working

### ISSUE THREAD

**Issue by gocursor** [leaningtech/webvm#6]
I can not interrupt any running command with CTRL+C.

**Comment by mhnsn** [comment]
Add to this: on Firefox, most anything other than `ls`, `dir`, and `cd` seems to hang the console. Vim, cowsay, npm, nodejs - all hang the console with no way to interrupt.

**Comment by sere** [comment]
Thanks for the report.

@gocursor: CTRL+C not working is a known issue - it's bound to a signal, SIGINT. Signals are currently not implemented.

@mhnsn: webvm is working (for me) on firefox 96.0.2, for all the examples that are in the page and the commands you listed. WebVM on Firefox takes a bit longer than Chrome, but works nevertheless.

`apt` instead indeed locks CheerpX and hangs the machine. We are looking into fixing this behaviour. Please note, though, that for the moment WebVM has no network and sudo support, so it won't be possible to install programs even after the hang has been solved.

**Comment by alexp-sssup** [comment]
`Ctrl+C` is now supported. Try it out on https://webvm.io
