### ISSUE TITLE
Uncaught ReferenceError: DEVICE_TYPE is not defined

### ISSUE THREAD

**Issue by jbemmel** [leaningtech/webvm#69]
When deploying a fork, the GitHub actions seem to miss including this attribute

Uncaught ReferenceError: DEVICE_TYPE is not defined
    at HTMLScriptElement.runBash ((index):315:37)

**Comment by alexp-sssup** [comment]
Are you sure you have configured GitHub Pages to deploy from Action, and not from branch. Please carefully follow the instructions here: https://github.com/leaningtech/webvm#fork-deploy-customize
