### ISSUE TITLE
Mobile app wrapper

### ISSUE THREAD

**Issue by luisdavim** [leaningtech/webvm#73]
This is not the same as https://github.com/leaningtech/webvm/issues/47

The idea would be to use this to have a linux terminal app running locally on a mobile device, similar to Termux on android but more isolated.

**Comment by alexp-sssup** [comment]
We are open to discussion if a third party wants to bring this to market using our technology, but our focus (and our expertise) is on Web use cases. The feature you suggests does not fit in our priorities at this time.
