### ISSUE TITLE
gcc fails to start with an Alpine image

### ISSUE THREAD

**Issue by mattx433** [leaningtech/webvm#77]
Running `/usr/bin/gcc` using an Alpine image hangs with the following error in the JS console:
```
Fault addr 4d4782b4, ip 555b777d, tid 14
Fault from Inode 22
```
Dockerfile: https://github.com/mattx433/webvm/blob/main/dockerfiles/alpine
Mini.WebVM with the above: https://mattx433.github.io/webvm/

**Comment by alexp-sssup** [comment]
This bug is also fixed with the latest build of CheerpX. There was a bug in the handling of non-PIC executable.
