### ISSUE TITLE
Su hangs indefinitely - and missing root password

### ISSUE THREAD

**Issue by PeterHindes** [leaningtech/webvm#8]
What is the su password for root

**Comment by naisanzaa** [comment]
```shell
user@:~$ sudo su -
bash: sudo: command not found
user@:~$ su -
Password: p
password
```

**Comment by sere** [comment]
Hello, thanks for the report. At the moment, `su` indeed causes the machine to hang.

Please note, though, that root access will not be available for the time being.

**Comment by rd6r4gdk24w729h5bdaz** [comment]
> Hello, thanks for the report. At the moment, `su` indeed causes the machine to hang.
> 
> Please note, though, that root access will not be available for the time being.

Why not?
Wath is the technical limitation?

**Comment by Alex-A137** [comment]
> Currently CheerpX doesn't support multiuser at all. There is only support for one user, and we decided to go with an unprivileged one (UID/GID 1000).

then add it

**Comment by alexp-sssup** [comment]
`su` is not supported on https://webvm.io

`root` (and `user`) password are `password`
