### ISSUE TITLE
Internet without Tailscale

### ISSUE THREAD

**Issue by jaulz** [leaningtech/webvm#81]
It would be great if there would be a way to access the Internet or at least proxy HTTP requests from the VM via the browser. Is that anything you are working on soon?

**Comment by alexp-sssup** [comment]
CORS limitations make it effectively impossible to use native browser HTTP support from the VM. We tried at length to find better solutions, but Tailscale was in the end the only viable option. We wrote at length about this: https://leaningtech.com/webvm-virtual-machine-with-networking-via-tailscale/

It is possible to use a self-hosted headscale setup, we offer that as an alternative solution to commercial users.

**Comment by jaulz** [comment]
Okay, thanks, that makes sense! 😊
