### ISSUE TITLE
Can I mount more then one ext2 block device?

### ISSUE THREAD

**Issue by yhw2003** [leaningtech/webvm#83]
I create a new empty ext2 image file, and mount it as 
``` js
CheerpXApp.create({devices:[{type:"bytes",url:"static/debian_mini_20230519_5022088024.ext2",name:"block1"},{type:"bytes",url:"static/extra.ext2",name:"block2"}],mounts:[{type:"ext2",dev:"block1",path:"/"},{type:"ext2",dev:"block2",path:"/extra"},{type:"cheerpOS",dev:"/app",path:"/app"},{type:"cheerpOS",dev:"/str",path:"/data"},{type:"devs",dev:"",path:"/dev"}], networkInterface: networkInterface, activityInterface: {cpu: cpuCallback, dev: devCallback}}).then(runTest, failCallback);
```
but I can do nothing on it in the VM
![](https://github.com/leaningtech/webvm/assets/46086392/667ddd38-9be8-4b4c-8e5e-15e7fbc14a71")

**Comment by alexp-sssup** [comment]
Can you try to mount it on an existing directory such as `/mnt/`

**Comment by yhw2003** [comment]
> 

That's not work. And got a same result.

**Comment by yhw2003** [comment]
> Can you try to mount it on an existing directory such as `/mnt/`?

I can mount the device block1 to multiple place, But i can't mount the block2.

**Comment by yhw2003** [comment]
> Can you try to mount it on an existing directory such as `/mnt/`?

That's not work. And got a same result.

**Comment by alexp-sssup** [comment]
How is the new ext2 image generated? Please try again with the following command:

`mkfs.ext2 -r 0 static/extra.ext2`

**Comment by yhw2003** [comment]
> How is the new ext2 image generated? Please try again with the following command:
> 
> `mkfs.ext2 -r 0 static/extra.ext2`

That worked,thanks,i didn't use the args"-r 0" maybe is this caused the error.

**Comment by alexp-sssup** [comment]
CheerpX currently only supports revision 0 of the Ext2 filesystem, hence the need for `-r 0` option.

This is visible in the GitHub Action steps as well: https://github.com/leaningtech/webvm/blob/main/.github/workflows/deploy.yml#L154

I am closing this issue. For further support please join our Discord: https://discord.gg/yTNZgySKGa
