### ISSUE TITLE
I'm not entirely sure how to call it

### ISSUE THREAD

**Issue by staviq** [leaningtech/webvm#85]
Just run `time echo aaa; time echo bbb`

It looks like memory alignment / integer type conversion problem, or ioctl is improperly stubbed and lands in absolutely random memory location:

```
user@:~/examples/python3$ time echo aaa ; time echo bbb
aaa

real    0m0.001s
user    0m0.000s
sys     23866502m23.((*s
bbb

real    0m0.001s
user    .-(**,*/m.).000s
sys     23866175m52.205s
user@:~/examples/python3$ 
```

**Comment by alexp-sssup** [comment]
Not all fields of the `tms` struct are currently populated by the `times` syscall. I'll ask a member of the team to take a look.

**Comment by alexp-sssup** [comment]
The bug is fixed in the currently deployed https://webvm.io, place make sure to clear your browser cache before trying again.

For further help: please join our Discord: https://discord.gg/yTNZgySKGa

**Comment by staviq** [comment]
Thank you, it seems to be fixed.

However, it's worth noting both Chromium and Firefox (including Android) do not seem to properly delete IndexedDB when clearing browser cache, I had to manually delete it with dev tools. And there currently seems to be no way of clearing IndexedDB on Android.
