### ISSUE TITLE
Access to internet

### ISSUE THREAD

**Issue by kenny1323** [leaningtech/webvm#86]
Hello. 
This Linux emulator, Buildroot, is able to connect to the network via  browser.
Run 
Udhcpc
ping 8.8.8.8 

#################
https://copy.sh/v86/
https://copy.sh/v86/?profile=buildroot
https://github.com/copy/v86

Buildroot Linux 5.0 MB.	
Minimal Linux with busybox, Lua, tests, internet access, ping, telnet and curl. 
Exchange files through /mnt/.

**Comment by yuri91** [comment]
Hi!

Webvm also can connect to the network via the Tailscale integration: https://github.com/leaningtech/webvm/blob/main/docs/Tailscale.md

You can find more info about our choice of using Tailscale in this article: https://leaningtech.com/webvm-virtual-machine-with-networking-via-tailscale/
