### ISSUE TITLE
Custom image (busybox) usage trouble

### ISSUE THREAD

**Issue by tarampampam** [leaningtech/webvm#87]
Hello there, and thanks for the awesome project!

I believe you can assist me in addressing the issue that arose during the custom image building process. Currently, I am utilizing the following script to generate the image:

```bash
#!/usr/bin/env sh
# reference: https://github.com/leaningtech/webvm/blob/e351ccdfa52c0e11580db90f4369c8691ef79c27/.github/workflows/deploy.yml

set -xe

# build the image
docker build --file ./Dockerfile --tag disk:local --platform=i386 .

# preallocate space for the ext2 image
fallocate -l 6M ./disk.ext2

# format to ext2 linux kernel revision 0
mkfs.ext2 -F -r 0 ./disk.ext2

# create a directory for the fs
mkdir ./mnt

# mount the ext2 image to modify it
sudo mount -o loop -t ext2 ./disk.ext2 ./mnt

# run the docker image so that we can export the container
CONTAINER_ID=$(docker run -d --dns 1.1.1.1 --dns 1.0.0.1 disk:local sleep 5m)

# copy image content
sudo docker cp -a $CONTAINER_ID:/ ./mnt/

# unmount & cleanup
docker kill $CONTAINER_ID
docker rmi -f disk:local
sudo umount ./mnt
sudo rm -Rf ./mnt
```

```dockerfile
# syntax=docker/dockerfile:1
FROM --platform=i386 docker.io/i386/busybox:1.35
```

However, when attempting to use this image on the JavaScript side, the console displays the following error:

![image](https://github.com/leaningtech/webvm/assets/7326800/33b60c8a-0bdb-4eea-b592-4b9a278048e9)

![image](https://github.com/leaningtech/webvm/assets/7326800/bc42603a-d311-4203-9322-8bcc9a9066f2)

When I switch the image to `https://disks.webvm.io/debian_large_20230522_5044875331.ext2`, everything works fine. Therefore, I believe the issue lies with the image itself, correct?

> Version: https://cheerpxdemos.leaningtech.com/publicdeploy/20230818_119/cx.js

P.S. I use the [CloudFlare pages](https://pages.cloudflare.com/) as a hosting

**Comment by alexp-sssup** [comment]
The `block` backend can only be used with our own image servers. For self deployment scenarios you need to use the `bytes` backend.

For further support consider joining our Discord: https://discord.gg/yTNZgySKGa

**Comment by alexp-sssup** [comment]
We are in the processing of expanding the docs, but this should really be all you need:

https://github.com/leaningtech/webvm#local-deployment

**Comment by tarampampam** [comment]
After switching on the `bytes` it still does not work :(

![image](https://github.com/leaningtech/webvm/assets/7326800/6a5d38c6-ef80-4c6d-bad5-efc21cff3ca2)

![image](https://github.com/leaningtech/webvm/assets/7326800/215e1ee7-83ff-4608-8998-582b29800f21)

**Comment by alexp-sssup** [comment]
Please use the network tab to make sure your web server is finding the image file and the `Content-Range` header is properly added.

**Comment by tarampampam** [comment]
Thanks for your answer! Is there any way to use as a device source something like Uint8Array? I mean in case I have a prefetched image - can I pass the image data directly to the `.create()`?

**Comment by alexp-sssup** [comment]
No, this latter use case is not supported. The block device infrastructure is designed for very large images which cannot be preloaded anyway.

In our view if a small image is needed the `bytes` backend will be sufficient anyway.

Please close this bug if the original issue is fixed and join the Discord for further help.
