### ISSUE TITLE
wget command makes the VM freak out

### ISSUE THREAD

**Issue by zek-c** [leaningtech/webvm#89]
just stops everything

**Comment by saarikoski-jules** [comment]
I am unable to reproduce this with the currently live WebVM. Please provide a screenshot of the broken state, with devtools console open, with the full command you ran visible. Are you possibly using a custom image?

**Comment by saarikoski-jules** [comment]
I'm glad to hear that you got it to work. It's possible that what you're seeing is just a delay. I'm closing this issue.
