### ISSUE TITLE
SharedArrayBuffer not available (even though it is)?

### ISSUE THREAD

**Issue by dsyer** [leaningtech/webvm#9]
Neat demo! I noticed that it works for me on webvm.io, but if I run it myself from source code (e.g. with `python -m http.server`) it fails on the `SharedArrayBuffer` test. So my browser _does_ support that feature, but something is preventing it from working. What gives?

**Comment by dsyer** [comment]
Nevermind. I get it - you need the `nginx.conf` settings.

**Comment by tennox** [comment]
More specifically, `SharedArrayBuffer` is only available on HTTPS - according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer)
