### ISSUE TITLE
 echo 1 > /app/ok hangs

### ISSUE THREAD

**Issue by Utopiah** [leaningtech/webvm#92]
Same behavior on local installation and on the public test server. No error message, just hanging.

**Comment by saarikoski-jules** [comment]
Thanks for reporting this issue. I do reproduce and will take a look when I'm able

**Comment by alexp-sssup** [comment]
The problem should be fixed and the new build is deployed on https://webvm.io

It might take some time for the CDN to propagate the change.

**Comment by Utopiah** [comment]
Indeed it's fixed, thanks! In order to learn a bit more about how all this works, what happened?

**Comment by alexp-sssup** [comment]
IIRC there was a bug in handling that `/app` is read-only when attempting to create a file. For further discussion I'd recommend joining our Discord: https://discord.gg/yTNZgySKGa
