### ISSUE TITLE
Trying to use CentOS i386 container : NOK

### ISSUE THREAD

**Issue by NonneTrapuE** [leaningtech/webvm#98]
Hi,

I try to use CentOS i386 Dockerfile with WebVM and Github Actions/Pages, but stay black screen. 
OS is not loaded ....
I change only DockerFile and deploy.yml to accept new Dockerfile ...
Ideas ?

Base image : 

https://hub.docker.com/r/i386/centos/ 

Thanks

**Comment by alexp-sssup** [comment]
There can be any number of issues, we need further information to help.

Consider placing your version on a publicly accessible URL, GitHub pages work.

You might have error messages in console as well. Also check the network tab to make sure the disk image data is found as expected.

**Comment by NonneTrapuE** [comment]
Public Page : https://nonnetrapue.github.io/webvm/

Deploy.yml : filehttps://github.com/NonneTrapuE/webvm/blob/main/.github/workflows/deploy.yml

Dockerfile : https://github.com/NonneTrapuE/webvm/blob/main/dockerfiles/centos_webvm


![image](https://github.com/leaningtech/webvm/assets/51425313/b88c5eb8-03b9-4ce3-97ac-cb276eea5f30)

Deploy and building are ok...

Do you have the information you need?

**Comment by alexp-sssup** [comment]
There is nothing obviously wrong, we'll need to investigate the problem. Please keep the deployment up, we'll need some time before we'll be able to work on this due to deadlines on other projects.

**Comment by NonneTrapuE** [comment]
I keep up Pages.

Thanks for support !

**Comment by alexp-sssup** [comment]
The problem should be fixed in this build: https://cheerpxdemos.leaningtech.com/publicdeploy/20240307_134/cx.js

It might take some time for the CDN to propagate the change.

Thanks for your patience, for further discussion consider joining our Discord: https://discord.gg/yTNZgySKGa
